version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/Riskweather_web_v2/
    overwrite: yes
permissions:
  - object: /home/ubuntu/Riskweather_web_v2/
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: ./after-install.sh
      timeout: 1000
      runas: ubuntu
